### ISSUE TITLE
war包进入tomcat的问题

### ISSUE THREAD

**Issue by gitzhang** [izhangzhihao/SpringMVCWithJavaConfig#1]
大神，打包的war放进tomcat后感觉没有加载到application.yml文件，我在里面的配置失效了。

**Comment by izhangzhihao** [comment]
这个只是SpringMVC的项目，并不是完全的Spring Boot项目，只是用javaConfig做了配置，然后Spring Boot做了依赖管理(因为比较省事)，所以本质上还是普通的Spring项目，故application.yml确实无法生效，大概是我没说太清楚，如果你在学习spring boot，可以看这个https://github.com/izhangzhihao/SSMSeedProject

**Comment by izhangzhihao** [comment]
# 这次更新改了数据库配置，还有很多其它配置，完全去除了SpringBoot依赖，需要重新导入一遍项目才可以正常使用！

**Comment by gitzhang** [comment]
感谢您的回复。看到您发布新版本了，赶紧去学习一下。
